server:
    port: 8080
spring:
    application:
      name: "accounts"
    profiles:
        active: "prod"
    datasource:
        url: jdbc:mysql://localhost:3306/accountsdb
        username: root
        password: root
    jpa:
        show-sql: true
    sql:
      init:
        mode: always
    config:
        import: "optional:configserver:http://localhost:8071/"
    cloud:
        openfeign:
            circuitbreaker:
                enabled: true

build:
    version: "1.0"
management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readinessstate:
            enabled: true
        livenessstate:
            enabled: true
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true
    info:
      env:
          enabled: true


endpoints:
    shutdown:
        enable: true


eureka:
    instance:
        prefer-ip-address: true
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/

info:
  app:
      name: "accounts"
      description: "Bank Accounts Application"
      version: "1.0"

logging:
    level:
        com:
            bank:
                accounts: debug

resilience4j:
    circuitbreaker:
        configs:
            default:
                sliding-window-size: 10
                permitted-number-of-calls-in-half-open-state: 2
                failure-rate-threshold: 50
                wait-duration-in-open-state: 10000