spring:
  application:
    name:"configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        # native:
          # you can also add filepath and git repo
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/emredurrmus/config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


server:
  port: 8071

encrypt:
  key: "KJH34ASK34JDHG1JGQIS44CHS"
